services:
  - type: web
    name: media-backend
    runtime: python
    rootDir: cloudinary-backend      # Quan trọng: Chỉ đường dẫn tới thư mục backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: YOUTUBE_CHANNEL_ID
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false